baseURL = "http://www.teosoft.it/bluish-capsule-dev-pages"
languageCode = "en-us"
defaultContentLanguage = "en-us"

title = "Bluish capsule"
theme = "tranquilpeak"

metaDataFormat = "yaml"
# pygmentsStyle = "trac"
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

paginate = 7
canonifyurls = true

# disqusShortname = "hugo-tranquilpeak-theme"
# googleAnalytics = "UA-24994854-1"

[author]
  name = "Gabriele Teotino"
  bio = "Coding is frustrating, tedious and fun"
  job = "developer"
  location = "United Kingdom"
  picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"

[params]
  #subtitle = "Some inspirational quote here"
  #logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  #dateFormat = "January 2, 2006"
  #commit = false
  #rss = true
  #comments = false
  #readingTime = true
  #useHLJS = true

  #gcse = "005185449088889757369:5o44h-2knna"

  syntaxHighlighter = "highlight.js"

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "Some inspirational quote here"

  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 2

  coverImage = "images/cover.jpg"

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  # Default thumbnail image position (`right`, `left` or `bottom`)
  # define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "bottom"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = true

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "notes"
  name = "Notes"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-sticky-note\"></i>"
  url = "/note"
[[menu.main]]
  weight = 4
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-industry\"></i>"
  url = "project"
[[menu.main]]
  weight = 5
  identifier = "reviews"
  name = "Reviews"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-amazon\"></i>"
  url = "/review"
[[menu.main]]
  weight = 6
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 7
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 9
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/gabrieleteotino"
[[menu.links]]
  weight = 2
  identifier = "stackoverflow"
  name = "Stack Overflow"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
  url = "https://stackoverflow.com/users/2085504/deramko"
[[menu.links]]
  weight = 3
  identifier = "linkedin"
  name = "Linkedin"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
  url = "https://www.linkedin.com/in/gabrieleteotino/"

[[menu.misc]]
  weight = 1
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"
