baseURL = "https://www.teosoft.it/"
languageCode = "en-us"
title = "Bluish capsule"
theme = "beautifulhugo"

metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

googleAnalytics = "UA-24994854-1"

[params]
  subtitle = "Some inspirational quote here"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = true
  gcse = "005185449088889757369:5o44h-2knna"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[author]
  name = "Gabriele Teotino"
  website = "https://www.teosoft.it"
  github = "gabrieleteotino"
  stackoverflow = "users/2085504/deramko"

[[menu.main]]
  name = "Blog"
  url = "/post"
  weight = 1

[[menu.main]]
  name = "Notes"
  url = "/note"
  weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  weight = 3
[[menu.main]]
  parent = "projects"
  name = "Projects home"
  url = "project"
  weight = 1
[[menu.main]]
  parent = "projects"
  name = "Meccanici"
  url = "project/meccanici"
  weight = 2
[[menu.main]]
  parent = "projects"
  name = "DatingApp"
  url = "project/datingapp"
  weight = 3
[[menu.main]]
  parent = "projects"
  name = "JobSearchLog"
  url = "project/jobsearchlog"
  weight = 4
[[menu.main]]
  parent = "projects"
  name = "NgRx in depth"
  url = "project/ngrx-in-depth"
  weight = 5

[[menu.main]]
  name = "Reviews"
  url = "/review"
  weight = 4
